Parameters:
  InstanceType:
    Description: EC2 instance type configuration
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.smal
  ImageId:
    Description: AMI Identifier for EC2 Instance
    Type: String
    Default: ami-02d5619017b3e5162
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
  IPAddress:
    Type: AWS::EC2::EIP
Outputs:
  InstanceIPAddress:
    Description: EC2 public IP
    Value: !Ref IPAddress